import time
while True:
    print('***********')
    time.sleep(0.6)
    print('**********')
    time.sleep(0.6)
    print('*********')
    time.sleep(0.6)
    print('********')
    time.sleep(0.6)
    print('*******')
    time.sleep(0.6)
    print('******')
    time.sleep(0.6)
    print('*****')
    time.sleep(0.6)
    print('****')
    time.sleep(0.6)
    print('***')
    time.sleep(0.6)
    print('**')
    time.sleep(0.6)
    print('*')